### ISSUE TITLE
Plug-in stopped working

### ISSUE THREAD

**Issue by DanielG86** [amirlanesman/signalk-to-nfl#4]
After updating to the latest, the plug-in didn’t update my track anymore. I found the following in the server log:

Apr 16 22:30:00 2023-04-16T20:30:00.025Z signalk-to-nfl checking the track /home/pi/.signalk/node_modules/signalk-to-nfl/track/track.jsonl if should send 
Apr 16 22:30:00 2023-04-16T20:30:00.030Z signalk-to-nfl '/home/pi/.signalk/node_modules/signalk-to-nfl/track/track.jsonl'.size=21493 /home/pi/.signalk/node_modules/signalk-to-nfl/track/track.jsonl'.exists=true 
Apr 16 22:30:00 2023-04-16T20:30:00.031Z signalk-to-nfl testing internet connection 
Apr 16 22:30:00 2023-04-16T20:30:00.232Z signalk-to-nfl internet connection = true 
Apr 16 22:30:00 2023-04-16T20:30:00.235Z signalk-to-nfl sending the data 
Apr 16 22:30:00 SyntaxError: Unexpected token  in JSON at position 0 at JSON.parse (<anonymous>) at createTrack (/home/pi/.signalk/node_modules/signalk-to-nfl/index.js:398:26) at runMicrotasks (<anonymous>) at processTicksAndRejections (node:internal/process/task_queues:96:5) at async sendApiData (/home/pi/.signalk/node_modules/signalk-to-nfl/index.js:345:25)

**Comment by amirlanesman** [comment]
@DanielG86 Can you attach a copy of the track file?
it should be in your signalk directory under `<signalk_dir>/track/track.jsonl` unless you changed it.

**Comment by DanielG86** [comment]
Hello Amiirlanesman,

Please find attached. I had to copy it from my SignalK server, but it came across properly. The 7th line shows some odd entries, so this could be the cause?

BTW: the track was in .signalk/node_modules/signalk-to-nfl/track/track.jsonl

Thanks for your support!

￼

Met vriendelijke groet,

Daniel Goedhuis
06-52 52 50 62

**Comment by amirlanesman** [comment]
@DanielG86 i can’t see any attached file…

**Comment by DanielG86** [comment]
Once more. Hopefully this works better.

￼

Met vriendelijke groet,

Daniel Goedhuis
06-52 52 50 62

**Comment by amirlanesman** [comment]
@DanielG86 still nothing there. maybe try through github instead of email?

**Comment by DanielG86** [comment]
Aha, II see that the attachment isn't there in Github, although I did attach it in the regular mail.
I changed the file, by deleting the odd characters in line 7, and saved it, and now I don't have the original anymore. After doing that, the file was accepted and sent to NFL, and subsequently deleted, so that helped...

Below the corrected file, although I noticed now that my track shows some odd places. Maybe my GPS has some faulty fixes, because it happened today again.

[track.jsonl.txt](https://github.com/amirlanesman/signalk-to-nfl/files/11290204/track.jsonl.txt)
